// <auto-generated />
using System;
using Legislature.TrackingSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Legislature.TrackingSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LtsDbContext))]
    [Migration("20260905204414_AddWorkTaskPersistence")]
    partial class AddWorkTaskPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.AccessRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("RestrictedUserType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SetByKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("WorkTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkTaskId");

                    b.ToTable("access_restrictions", (string)null);
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Biennium")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsBudgetBill")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresImplementation")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BillNumber");

                    b.ToTable("bills", (string)null);
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.BillFiscalNoteLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkedByKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("WorkTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("bill_fiscal_note_links", (string)null);
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.Correspondence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BillId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("ResponseReceived")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SentByKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("WorkTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("correspondence", (string)null);
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.CustomReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OwnerKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerKey");

                    b.ToTable("custom_reports", (string)null);
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.DemographicData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Session", "Category")
                        .IsUnique();

                    b.ToTable("demographic_data", (string)null);
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.DocumentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicableWorkType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("document_templates", (string)null);
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.EmailDispatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SentByKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("SentAt");

                    b.ToTable("email_dispatches", (string)null);
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.ExecutiveDiscussion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AnsweredByKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("AssociatedWorkTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("executive_discussions", (string)null);
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.ExpenseEstimateElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Kind");

                    b.ToTable("expense_estimate_elements", (string)null);
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.FiscalData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Source")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Name");

                    b.ToTable("fiscal_data", (string)null);
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.FiscalWorkPaper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("WorkTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkTaskId");

                    b.ToTable("fiscal_work_papers", (string)null);
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.ImplementationTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedByKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<string>("Division")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("RequiredWork")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("implementation_tasks", (string)null);
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.LegacyMigrationBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImportedByKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("legacy_migration_batches", (string)null);
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipientKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientKey");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("packages", (string)null);
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("UserKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserKey")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.WorkItemRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SourceItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("SourceItemId");

                    b.ToTable("work_item_relationships", (string)null);
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.WorkTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("CustomerDueDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("ExecutiveReviewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsConfidential")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExecutiveReview")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Owner")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.PrimitiveCollection<string[]>("RequiredReviewerKeyValues")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("RequiredReviewerKeys");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkflowStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.HasIndex("Year");

                    b.ToTable("work_tasks", (string)null);
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.Bill", b =>
                {
                    b.OwnsMany("Legislature.TrackingSystem.Domain.WorkItems.BillAmendment", "Amendments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("AmendmentNumber")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<Guid>("BillId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CapturedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Source")
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("BillId");

                            b1.ToTable("bill_amendments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsMany("Legislature.TrackingSystem.Domain.WorkItems.BillVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("BillId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CapturedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Source")
                                .HasColumnType("text");

                            b1.Property<string>("VersionLabel")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.HasKey("Id");

                            b1.HasIndex("BillId");

                            b1.ToTable("bill_versions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.Navigation("Amendments");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.ImplementationTask", b =>
                {
                    b.OwnsMany("Legislature.TrackingSystem.Domain.WorkItems.SharedDocument", "SharedDocuments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<Guid>("ImplementationTaskId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("SharedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SharedByKey")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("ImplementationTaskId");

                            b1.ToTable("shared_documents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ImplementationTaskId");
                        });

                    b.Navigation("SharedDocuments");
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.LegacyMigrationBatch", b =>
                {
                    b.OwnsMany("Legislature.TrackingSystem.Domain.WorkItems.MigrationRecord", "Records", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("BatchId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("BatchOwnerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Note")
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)");

                            b1.Property<string>("SourceKey")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<Guid?>("TargetWorkTaskId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("BatchId");

                            b1.HasIndex("BatchOwnerId");

                            b1.ToTable("migration_records", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BatchOwnerId");
                        });

                    b.Navigation("Records");
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.Package", b =>
                {
                    b.OwnsMany("Legislature.TrackingSystem.Domain.WorkItems.PackageMember", "Members", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTimeOffset>("AddedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("AddedByKey")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<Guid>("PackageId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("WorkItemId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("PackageId");

                            b1.ToTable("package_members", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PackageId");
                        });

                    b.OwnsMany("Legislature.TrackingSystem.Domain.WorkItems.PackageRecipient", "Recipients", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("AddedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<Guid>("PackageId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("PackageId");

                            b1.ToTable("package_recipients", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PackageId");
                        });

                    b.Navigation("Members");

                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("Legislature.TrackingSystem.Domain.WorkItems.WorkTask", b =>
                {
                    b.OwnsOne("Legislature.TrackingSystem.Domain.Traceability.SourceTraceReference", "SourceTrace", b1 =>
                        {
                            b1.Property<Guid>("WorkTaskId")
                                .HasColumnType("uuid");

                            b1.Property<string>("RequirementId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("RequirementId");

                            b1.Property<string>("RequirementType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("RequirementType");

                            b1.Property<string>("SourceDocument")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("SourceDocument");

                            b1.Property<string>("StoryId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("StoryId");

                            b1.HasKey("WorkTaskId");

                            b1.ToTable("work_tasks");

                            b1.WithOwner()
                                .HasForeignKey("WorkTaskId");
                        });

                    b.OwnsMany("Legislature.TrackingSystem.Domain.WorkItems.Attachment", "Attachments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("AddedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("AddedByKey")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint");

                            b1.Property<Guid>("WorkTaskId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkTaskId");

                            b1.ToTable("work_task_attachments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkTaskId");
                        });

                    b.OwnsMany("Legislature.TrackingSystem.Domain.WorkItems.ExecutiveReviewAdjustment", "AdjustmentNotes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("AdjustedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Note")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)");

                            b1.Property<string>("ReviewerKey")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<Guid>("WorkTaskId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkTaskId");

                            b1.ToTable("executive_review_adjustments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkTaskId");
                        });

                    b.OwnsMany("Legislature.TrackingSystem.Domain.WorkItems.ExecutiveReviewer", "ExecutiveReviewers", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Comment")
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)");

                            b1.Property<DateTimeOffset?>("CompletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("ReviewOrder");

                            b1.Property<string>("ReviewerKey")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<Guid>("WorkTaskId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkTaskId");

                            b1.ToTable("executive_reviewers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkTaskId");
                        });

                    b.OwnsMany("Legislature.TrackingSystem.Domain.WorkItems.TaskAssignment", "Assignments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("AssignedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("AssignedByKey")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("AssigneeKey")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<DateOnly?>("DueDate")
                                .HasColumnType("date");

                            b1.Property<bool>("IsRework")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsSuperseded")
                                .HasColumnType("boolean");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<Guid>("WorkTaskId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkTaskId");

                            b1.ToTable("work_task_assignments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkTaskId");
                        });

                    b.OwnsMany("Legislature.TrackingSystem.Domain.WorkItems.WorkTaskAuditEntry", "AuditEntries", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ByKey")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Detail")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("WorkTaskId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkTaskId");

                            b1.ToTable("work_task_audit_entries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkTaskId");
                        });

                    b.OwnsMany("Legislature.TrackingSystem.Domain.WorkItems.WorkTaskComment", "Comments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("AuthorKey")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("WorkTaskId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkTaskId");

                            b1.ToTable("work_task_comments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkTaskId");
                        });

                    b.OwnsMany("Legislature.TrackingSystem.Domain.WorkItems.WorkTaskVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CapturedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CapturedByKey")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Content")
                                .HasColumnType("text");

                            b1.Property<int>("VersionNumber")
                                .HasColumnType("integer");

                            b1.Property<Guid>("WorkTaskId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkTaskId");

                            b1.ToTable("work_task_versions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkTaskId");
                        });

                    b.OwnsMany("Legislature.TrackingSystem.Domain.WorkItems.WorkflowReview", "Reviews", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Comment")
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)");

                            b1.Property<string>("Decision")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<DateTimeOffset>("ReviewedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ReviewerKey")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<Guid>("WorkTaskId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkTaskId");

                            b1.ToTable("workflow_reviews", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkTaskId");
                        });

                    b.OwnsMany("Legislature.TrackingSystem.Domain.WorkItems.WorkflowStep", "Steps", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("DueDate")
                                .HasColumnType("date");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<Guid>("WorkTaskId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkTaskId");

                            b1.ToTable("workflow_steps", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkTaskId");
                        });

                    b.Navigation("AdjustmentNotes");

                    b.Navigation("Assignments");

                    b.Navigation("Attachments");

                    b.Navigation("AuditEntries");

                    b.Navigation("Comments");

                    b.Navigation("ExecutiveReviewers");

                    b.Navigation("Reviews");

                    b.Navigation("SourceTrace")
                        .IsRequired();

                    b.Navigation("Steps");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
